### ISSUE TITLE
Generated docs for patio.sql.json

### ISSUE THREAD

**Issue by ruzz311** [C2FO/patio#126]
Not sure there's a real ask here but maybe just some doc clean up to fix confusion.

The class definition for patio.sql.Json and patio.sql.JsonArray seem to be broken:
- http://c2fo.github.io/patio/patio_sql_Json.html 
- http://c2fo.github.io/patio/patio_sql_JsonArray.html

However there is a pretty thorough explanation of the json class under patio.sql class definition:
- http://c2fo.github.io/patio/patio_sql.html#.json

**Comment by vikeen** [comment]
We'll take a big sweep through docs and examples for the next release.
